### ISSUE TITLE
Login Problem

### ISSUE THREAD

**Issue by marcomameli1992** [lesander/fbgs#1]
Dear, I'm trying to use your code. I have a problem with login. After the click on the button facebook shows me the save button to save the access and on this show there is a problem that do not permit to access on the social network.

**Comment by lesander** [comment]
Hi Marco, thank you for creating this issue. Could you share a screenshot of the browser instance and the log output from the script?

**Comment by lesander** [comment]
Hi Marco, I'm closing this issue as I haven't heard back from you. Please re-open this when you have more information to share in regards to the problem you experienced.
